// Auto-generated Image components
export { BuildInSimImage, default as BuildInSimImageDefault } from './BuildInSimImage';
export { BuildInSim2xImage, default as BuildInSim2xImageDefault } from './BuildInSim2xImage';
export { BuildInSim3xImage, default as BuildInSim3xImageDefault } from './BuildInSim3xImage';
export { Cm100glteImage, default as Cm100glteImageDefault } from './Cm100glteImage';
export { Cm100glte2xImage, default as Cm100glte2xImageDefault } from './Cm100glte2xImage';
export { Cm100glte3xImage, default as Cm100glte3xImageDefault } from './Cm100glte3xImage';
export { ConnectedGraphic1Image, default as ConnectedGraphic1ImageDefault } from './ConnectedGraphic1Image';
export { ConnectedGraphic2Image, default as ConnectedGraphic2ImageDefault } from './ConnectedGraphic2Image';
export { ConnectedGraphic3Image, default as ConnectedGraphic3ImageDefault } from './ConnectedGraphic3Image';
export { ConnectedGraphicImage, default as ConnectedGraphicImageDefault } from './ConnectedGraphicImage';
export { ConnectedGraphic2x1Image, default as ConnectedGraphic2x1ImageDefault } from './ConnectedGraphic2x1Image';
export { ConnectedGraphic2x2Image, default as ConnectedGraphic2x2ImageDefault } from './ConnectedGraphic2x2Image';
export { ConnectedGraphic2x3Image, default as ConnectedGraphic2x3ImageDefault } from './ConnectedGraphic2x3Image';
export { ConnectedGraphic2xImage, default as ConnectedGraphic2xImageDefault } from './ConnectedGraphic2xImage';
export { ConnectedGraphic3x1Image, default as ConnectedGraphic3x1ImageDefault } from './ConnectedGraphic3x1Image';
export { ConnectedGraphic3x2Image, default as ConnectedGraphic3x2ImageDefault } from './ConnectedGraphic3x2Image';
export { ConnectedGraphic3x3Image, default as ConnectedGraphic3x3ImageDefault } from './ConnectedGraphic3x3Image';
export { ConnectedGraphic3xImage, default as ConnectedGraphic3xImageDefault } from './ConnectedGraphic3xImage';
export { DashCamBlacklistedImage, default as DashCamBlacklistedImageDefault } from './DashCamBlacklistedImage';
export { DashCamBlacklisted2xImage, default as DashCamBlacklisted2xImageDefault } from './DashCamBlacklisted2xImage';
export { DashCamBlacklisted3xImage, default as DashCamBlacklisted3xImageDefault } from './DashCamBlacklisted3xImage';
export { DashCamFailedImage, default as DashCamFailedImageDefault } from './DashCamFailedImage';
export { DashCamFailed2xImage, default as DashCamFailed2xImageDefault } from './DashCamFailed2xImage';
export { DashCamFailed3xImage, default as DashCamFailed3xImageDefault } from './DashCamFailed3xImage';
export { DashcamerablackvueImage, default as DashcamerablackvueImageDefault } from './DashcamerablackvueImage';
export { Dashcamerablackvue2xImage, default as Dashcamerablackvue2xImageDefault } from './Dashcamerablackvue2xImage';
export { Dashcamerablackvue3xImage, default as Dashcamerablackvue3xImageDefault } from './Dashcamerablackvue3xImage';
export { FleetadriveuploaddarkImage, default as FleetadriveuploaddarkImageDefault } from './FleetadriveuploaddarkImage';
export { Fleetadriveuploaddark2xImage, default as Fleetadriveuploaddark2xImageDefault } from './Fleetadriveuploaddark2xImage';
export { Fleetadriveuploaddark3xImage, default as Fleetadriveuploaddark3xImageDefault } from './Fleetadriveuploaddark3xImage';
export { FleetadriveuploadlightImage, default as FleetadriveuploadlightImageDefault } from './FleetadriveuploadlightImage';
export { Fleetadriveuploadlight2xImage, default as Fleetadriveuploadlight2xImageDefault } from './Fleetadriveuploadlight2xImage';
export { Fleetadriveuploadlight3xImage, default as Fleetadriveuploadlight3xImageDefault } from './Fleetadriveuploadlight3xImage';
export { LiveeventuploadImage, default as LiveeventuploadImageDefault } from './LiveeventuploadImage';
export { LiveeventuploaddarkImage, default as LiveeventuploaddarkImageDefault } from './LiveeventuploaddarkImage';
export { Liveeventuploaddark2xImage, default as Liveeventuploaddark2xImageDefault } from './Liveeventuploaddark2xImage';
export { Liveeventuploaddark3xImage, default as Liveeventuploaddark3xImageDefault } from './Liveeventuploaddark3xImage';
export { Liveeventuploadlight2xImage, default as Liveeventuploadlight2xImageDefault } from './Liveeventuploadlight2xImage';
export { Liveeventuploadlight3xImage, default as Liveeventuploadlight3xImageDefault } from './Liveeventuploadlight3xImage';
export { MydriveuploaddarkImage, default as MydriveuploaddarkImageDefault } from './MydriveuploaddarkImage';
export { Mydriveuploaddark2xImage, default as Mydriveuploaddark2xImageDefault } from './Mydriveuploaddark2xImage';
export { Mydriveuploaddark3xImage, default as Mydriveuploaddark3xImageDefault } from './Mydriveuploaddark3xImage';
export { MydriveuploadlightImage, default as MydriveuploadlightImageDefault } from './MydriveuploadlightImage';
export { Mydriveuploadlight2xImage, default as Mydriveuploadlight2xImageDefault } from './Mydriveuploadlight2xImage';
export { Mydriveuploadlight3xImage, default as Mydriveuploadlight3xImageDefault } from './Mydriveuploadlight3xImage';
export { SimiccidpositionImage, default as SimiccidpositionImageDefault } from './SimiccidpositionImage';
export { Simiccidposition2xImage, default as Simiccidposition2xImageDefault } from './Simiccidposition2xImage';
export { Simiccidposition3xImage, default as Simiccidposition3xImageDefault } from './Simiccidposition3xImage';
export { SeamlessofffaileddarkImage, default as SeamlessofffaileddarkImageDefault } from './SeamlessofffaileddarkImage';
export { Seamlessofffaileddark2xImage, default as Seamlessofffaileddark2xImageDefault } from './Seamlessofffaileddark2xImage';
export { Seamlessofffaileddark3xImage, default as Seamlessofffaileddark3xImageDefault } from './Seamlessofffaileddark3xImage';
export { SeamlessofffailedlightImage, default as SeamlessofffailedlightImageDefault } from './SeamlessofffailedlightImage';
export { Seamlessofffailedlight2xImage, default as Seamlessofffailedlight2xImageDefault } from './Seamlessofffailedlight2xImage';
export { Seamlessofffailedlight3xImage, default as Seamlessofffailedlight3xImageDefault } from './Seamlessofffailedlight3xImage';
export { SensortouchdarkblackvueImage, default as SensortouchdarkblackvueImageDefault } from './SensortouchdarkblackvueImage';
export { Sensortouchdarkblackvue2xImage, default as Sensortouchdarkblackvue2xImageDefault } from './Sensortouchdarkblackvue2xImage';
export { Sensortouchdarkblackvue3xImage, default as Sensortouchdarkblackvue3xImageDefault } from './Sensortouchdarkblackvue3xImage';
export { SensortouchdarkfleetaImage, default as SensortouchdarkfleetaImageDefault } from './SensortouchdarkfleetaImage';
export { Sensortouchdarkfleeta2xImage, default as Sensortouchdarkfleeta2xImageDefault } from './Sensortouchdarkfleeta2xImage';
export { Sensortouchdarkfleeta3xImage, default as Sensortouchdarkfleeta3xImageDefault } from './Sensortouchdarkfleeta3xImage';
export { SensortouchlightblackvueImage, default as SensortouchlightblackvueImageDefault } from './SensortouchlightblackvueImage';
export { Sensortouchlightblackvue2xImage, default as Sensortouchlightblackvue2xImageDefault } from './Sensortouchlightblackvue2xImage';
export { Sensortouchlightblackvue3xImage, default as Sensortouchlightblackvue3xImageDefault } from './Sensortouchlightblackvue3xImage';
export { SensortouchlightfleetaImage, default as SensortouchlightfleetaImageDefault } from './SensortouchlightfleetaImage';
export { Sensortouchlightfleeta2xImage, default as Sensortouchlightfleeta2xImageDefault } from './Sensortouchlightfleeta2xImage';
export { Sensortouchlightfleeta3xImage, default as Sensortouchlightfleeta3xImageDefault } from './Sensortouchlightfleeta3xImage';
export { WifiHotspotImage, default as WifiHotspotImageDefault } from './WifiHotspotImage';
export { WifiHotspot2xImage, default as WifiHotspot2xImageDefault } from './WifiHotspot2xImage';
export { WifiHotspot3xImage, default as WifiHotspot3xImageDefault } from './WifiHotspot3xImage';

// Type exports
export type { BuildInSimImageProps } from './BuildInSimImage';
export type { BuildInSim2xImageProps } from './BuildInSim2xImage';
export type { BuildInSim3xImageProps } from './BuildInSim3xImage';
export type { Cm100glteImageProps } from './Cm100glteImage';
export type { Cm100glte2xImageProps } from './Cm100glte2xImage';
export type { Cm100glte3xImageProps } from './Cm100glte3xImage';
export type { ConnectedGraphic1ImageProps } from './ConnectedGraphic1Image';
export type { ConnectedGraphic2ImageProps } from './ConnectedGraphic2Image';
export type { ConnectedGraphic3ImageProps } from './ConnectedGraphic3Image';
export type { ConnectedGraphicImageProps } from './ConnectedGraphicImage';
export type { ConnectedGraphic2x1ImageProps } from './ConnectedGraphic2x1Image';
export type { ConnectedGraphic2x2ImageProps } from './ConnectedGraphic2x2Image';
export type { ConnectedGraphic2x3ImageProps } from './ConnectedGraphic2x3Image';
export type { ConnectedGraphic2xImageProps } from './ConnectedGraphic2xImage';
export type { ConnectedGraphic3x1ImageProps } from './ConnectedGraphic3x1Image';
export type { ConnectedGraphic3x2ImageProps } from './ConnectedGraphic3x2Image';
export type { ConnectedGraphic3x3ImageProps } from './ConnectedGraphic3x3Image';
export type { ConnectedGraphic3xImageProps } from './ConnectedGraphic3xImage';
export type { DashCamBlacklistedImageProps } from './DashCamBlacklistedImage';
export type { DashCamBlacklisted2xImageProps } from './DashCamBlacklisted2xImage';
export type { DashCamBlacklisted3xImageProps } from './DashCamBlacklisted3xImage';
export type { DashCamFailedImageProps } from './DashCamFailedImage';
export type { DashCamFailed2xImageProps } from './DashCamFailed2xImage';
export type { DashCamFailed3xImageProps } from './DashCamFailed3xImage';
export type { DashcamerablackvueImageProps } from './DashcamerablackvueImage';
export type { Dashcamerablackvue2xImageProps } from './Dashcamerablackvue2xImage';
export type { Dashcamerablackvue3xImageProps } from './Dashcamerablackvue3xImage';
export type { FleetadriveuploaddarkImageProps } from './FleetadriveuploaddarkImage';
export type { Fleetadriveuploaddark2xImageProps } from './Fleetadriveuploaddark2xImage';
export type { Fleetadriveuploaddark3xImageProps } from './Fleetadriveuploaddark3xImage';
export type { FleetadriveuploadlightImageProps } from './FleetadriveuploadlightImage';
export type { Fleetadriveuploadlight2xImageProps } from './Fleetadriveuploadlight2xImage';
export type { Fleetadriveuploadlight3xImageProps } from './Fleetadriveuploadlight3xImage';
export type { LiveeventuploadImageProps } from './LiveeventuploadImage';
export type { LiveeventuploaddarkImageProps } from './LiveeventuploaddarkImage';
export type { Liveeventuploaddark2xImageProps } from './Liveeventuploaddark2xImage';
export type { Liveeventuploaddark3xImageProps } from './Liveeventuploaddark3xImage';
export type { Liveeventuploadlight2xImageProps } from './Liveeventuploadlight2xImage';
export type { Liveeventuploadlight3xImageProps } from './Liveeventuploadlight3xImage';
export type { MydriveuploaddarkImageProps } from './MydriveuploaddarkImage';
export type { Mydriveuploaddark2xImageProps } from './Mydriveuploaddark2xImage';
export type { Mydriveuploaddark3xImageProps } from './Mydriveuploaddark3xImage';
export type { MydriveuploadlightImageProps } from './MydriveuploadlightImage';
export type { Mydriveuploadlight2xImageProps } from './Mydriveuploadlight2xImage';
export type { Mydriveuploadlight3xImageProps } from './Mydriveuploadlight3xImage';
export type { SimiccidpositionImageProps } from './SimiccidpositionImage';
export type { Simiccidposition2xImageProps } from './Simiccidposition2xImage';
export type { Simiccidposition3xImageProps } from './Simiccidposition3xImage';
export type { SeamlessofffaileddarkImageProps } from './SeamlessofffaileddarkImage';
export type { Seamlessofffaileddark2xImageProps } from './Seamlessofffaileddark2xImage';
export type { Seamlessofffaileddark3xImageProps } from './Seamlessofffaileddark3xImage';
export type { SeamlessofffailedlightImageProps } from './SeamlessofffailedlightImage';
export type { Seamlessofffailedlight2xImageProps } from './Seamlessofffailedlight2xImage';
export type { Seamlessofffailedlight3xImageProps } from './Seamlessofffailedlight3xImage';
export type { SensortouchdarkblackvueImageProps } from './SensortouchdarkblackvueImage';
export type { Sensortouchdarkblackvue2xImageProps } from './Sensortouchdarkblackvue2xImage';
export type { Sensortouchdarkblackvue3xImageProps } from './Sensortouchdarkblackvue3xImage';
export type { SensortouchdarkfleetaImageProps } from './SensortouchdarkfleetaImage';
export type { Sensortouchdarkfleeta2xImageProps } from './Sensortouchdarkfleeta2xImage';
export type { Sensortouchdarkfleeta3xImageProps } from './Sensortouchdarkfleeta3xImage';
export type { SensortouchlightblackvueImageProps } from './SensortouchlightblackvueImage';
export type { Sensortouchlightblackvue2xImageProps } from './Sensortouchlightblackvue2xImage';
export type { Sensortouchlightblackvue3xImageProps } from './Sensortouchlightblackvue3xImage';
export type { SensortouchlightfleetaImageProps } from './SensortouchlightfleetaImage';
export type { Sensortouchlightfleeta2xImageProps } from './Sensortouchlightfleeta2xImage';
export type { Sensortouchlightfleeta3xImageProps } from './Sensortouchlightfleeta3xImage';
export type { WifiHotspotImageProps } from './WifiHotspotImage';
export type { WifiHotspot2xImageProps } from './WifiHotspot2xImage';
export type { WifiHotspot3xImageProps } from './WifiHotspot3xImage';

// Utility types
export interface ImageComponentProps {
  className?: string;
  width?: number | string;
  height?: number | string;
  alt?: string;
  style?: React.CSSProperties;
  onClick?: () => void;
  onLoad?: () => void;
  onError?: () => void;
}

export interface LazyImageProps extends ImageComponentProps {
  lazy?: boolean;
  placeholder?: React.ReactNode;
  cdnBase?: string;
}
