// Auto-generated Image components
export { BuildInSimImage, default as BuildInSimImageDefault } from './BuildInSimImage';
export { BuildInSim2xImage, default as BuildInSim2xImageDefault } from './BuildInSim2xImage';
export { BuildInSim3xImage, default as BuildInSim3xImageDefault } from './BuildInSim3xImage';
export { Cm100glteImage, default as Cm100glteImageDefault } from './Cm100glteImage';
export { Cm100glte2xImage, default as Cm100glte2xImageDefault } from './Cm100glte2xImage';
export { Cm100glte3xImage, default as Cm100glte3xImageDefault } from './Cm100glte3xImage';
export { ConnectedGraphic1Image, default as ConnectedGraphic1ImageDefault } from './ConnectedGraphic1Image';
export { ConnectedGraphic2Image, default as ConnectedGraphic2ImageDefault } from './ConnectedGraphic2Image';
export { ConnectedGraphic3Image, default as ConnectedGraphic3ImageDefault } from './ConnectedGraphic3Image';
export { ConnectedGraphicImage, default as ConnectedGraphicImageDefault } from './ConnectedGraphicImage';
export { ConnectedGraphic2x1Image, default as ConnectedGraphic2x1ImageDefault } from './ConnectedGraphic2x1Image';
export { ConnectedGraphic2x2Image, default as ConnectedGraphic2x2ImageDefault } from './ConnectedGraphic2x2Image';
export { ConnectedGraphic2x3Image, default as ConnectedGraphic2x3ImageDefault } from './ConnectedGraphic2x3Image';
export { ConnectedGraphic2xImage, default as ConnectedGraphic2xImageDefault } from './ConnectedGraphic2xImage';
export { ConnectedGraphic3x1Image, default as ConnectedGraphic3x1ImageDefault } from './ConnectedGraphic3x1Image';
export { ConnectedGraphic3x2Image, default as ConnectedGraphic3x2ImageDefault } from './ConnectedGraphic3x2Image';
export { ConnectedGraphic3x3Image, default as ConnectedGraphic3x3ImageDefault } from './ConnectedGraphic3x3Image';
export { ConnectedGraphic3xImage, default as ConnectedGraphic3xImageDefault } from './ConnectedGraphic3xImage';
export { DashCamBlacklistedImage, default as DashCamBlacklistedImageDefault } from './DashCamBlacklistedImage';
export { DashCamBlacklisted2xImage, default as DashCamBlacklisted2xImageDefault } from './DashCamBlacklisted2xImage';
export { DashCamBlacklisted3xImage, default as DashCamBlacklisted3xImageDefault } from './DashCamBlacklisted3xImage';
export { DashCamFailedImage, default as DashCamFailedImageDefault } from './DashCamFailedImage';
export { DashCamFailed2xImage, default as DashCamFailed2xImageDefault } from './DashCamFailed2xImage';
export { DashCamFailed3xImage, default as DashCamFailed3xImageDefault } from './DashCamFailed3xImage';
export { FilelistTipsSensorTouchBlackvue1Image, default as FilelistTipsSensorTouchBlackvue1ImageDefault } from './FilelistTipsSensorTouchBlackvue1Image';
export { FilelistTipsSensorTouchBlackvueImage, default as FilelistTipsSensorTouchBlackvueImageDefault } from './FilelistTipsSensorTouchBlackvueImage';
export { FilelistTipsSensorTouchBlackvue2x1Image, default as FilelistTipsSensorTouchBlackvue2x1ImageDefault } from './FilelistTipsSensorTouchBlackvue2x1Image';
export { FilelistTipsSensorTouchBlackvue2xImage, default as FilelistTipsSensorTouchBlackvue2xImageDefault } from './FilelistTipsSensorTouchBlackvue2xImage';
export { FilelistTipsSensorTouchBlackvue3x1Image, default as FilelistTipsSensorTouchBlackvue3x1ImageDefault } from './FilelistTipsSensorTouchBlackvue3x1Image';
export { FilelistTipsSensorTouchBlackvue3xImage, default as FilelistTipsSensorTouchBlackvue3xImageDefault } from './FilelistTipsSensorTouchBlackvue3xImage';
export { FilelistTipsSensorTouchFleeta1Image, default as FilelistTipsSensorTouchFleeta1ImageDefault } from './FilelistTipsSensorTouchFleeta1Image';
export { FilelistTipsSensorTouchFleetaImage, default as FilelistTipsSensorTouchFleetaImageDefault } from './FilelistTipsSensorTouchFleetaImage';
export { FilelistTipsSensorTouchFleeta2x1Image, default as FilelistTipsSensorTouchFleeta2x1ImageDefault } from './FilelistTipsSensorTouchFleeta2x1Image';
export { FilelistTipsSensorTouchFleeta2xImage, default as FilelistTipsSensorTouchFleeta2xImageDefault } from './FilelistTipsSensorTouchFleeta2xImage';
export { FilelistTipsSensorTouchFleeta3x1Image, default as FilelistTipsSensorTouchFleeta3x1ImageDefault } from './FilelistTipsSensorTouchFleeta3x1Image';
export { FilelistTipsSensorTouchFleeta3xImage, default as FilelistTipsSensorTouchFleeta3xImageDefault } from './FilelistTipsSensorTouchFleeta3xImage';
export { SimIccidImage344Image, default as SimIccidImage344ImageDefault } from './SimIccidImage344Image';
export { SimIccidImage3442xImage, default as SimIccidImage3442xImageDefault } from './SimIccidImage3442xImage';
export { SimIccidImage3443xImage, default as SimIccidImage3443xImageDefault } from './SimIccidImage3443xImage';
export { SimIccidImage345Image, default as SimIccidImage345ImageDefault } from './SimIccidImage345Image';
export { SimIccidImage3452xImage, default as SimIccidImage3452xImageDefault } from './SimIccidImage3452xImage';
export { SimIccidImage3453xImage, default as SimIccidImage3453xImageDefault } from './SimIccidImage3453xImage';
export { TouchSensorImage, default as TouchSensorImageDefault } from './TouchSensorImage';
export { TouchSensor2xImage, default as TouchSensor2xImageDefault } from './TouchSensor2xImage';
export { TouchSensor3xImage, default as TouchSensor3xImageDefault } from './TouchSensor3xImage';
export { WifiHotspotImage, default as WifiHotspotImageDefault } from './WifiHotspotImage';
export { WifiHotspot2xImage, default as WifiHotspot2xImageDefault } from './WifiHotspot2xImage';
export { WifiHotspot3xImage, default as WifiHotspot3xImageDefault } from './WifiHotspot3xImage';
export { DarkModeFalse1Image, default as DarkModeFalse1ImageDefault } from './DarkModeFalse1Image';
export { DarkModeFalse2Image, default as DarkModeFalse2ImageDefault } from './DarkModeFalse2Image';
export { DarkModeFalseImage, default as DarkModeFalseImageDefault } from './DarkModeFalseImage';
export { DarkModeFalse2x1Image, default as DarkModeFalse2x1ImageDefault } from './DarkModeFalse2x1Image';
export { DarkModeFalse2x2Image, default as DarkModeFalse2x2ImageDefault } from './DarkModeFalse2x2Image';
export { DarkModeFalse2xImage, default as DarkModeFalse2xImageDefault } from './DarkModeFalse2xImage';
export { DarkModeFalse3x1Image, default as DarkModeFalse3x1ImageDefault } from './DarkModeFalse3x1Image';
export { DarkModeFalse3x2Image, default as DarkModeFalse3x2ImageDefault } from './DarkModeFalse3x2Image';
export { DarkModeFalse3xImage, default as DarkModeFalse3xImageDefault } from './DarkModeFalse3xImage';
export { DarkModeTrue1Image, default as DarkModeTrue1ImageDefault } from './DarkModeTrue1Image';
export { DarkModeTrue2Image, default as DarkModeTrue2ImageDefault } from './DarkModeTrue2Image';
export { DarkModeTrueImage, default as DarkModeTrueImageDefault } from './DarkModeTrueImage';
export { DarkModeTrue2x1Image, default as DarkModeTrue2x1ImageDefault } from './DarkModeTrue2x1Image';
export { DarkModeTrue2x2Image, default as DarkModeTrue2x2ImageDefault } from './DarkModeTrue2x2Image';
export { DarkModeTrue2xImage, default as DarkModeTrue2xImageDefault } from './DarkModeTrue2xImage';
export { DarkModeTrue3x1Image, default as DarkModeTrue3x1ImageDefault } from './DarkModeTrue3x1Image';
export { DarkModeTrue3x2Image, default as DarkModeTrue3x2ImageDefault } from './DarkModeTrue3x2Image';
export { DarkModeTrue3xImage, default as DarkModeTrue3xImageDefault } from './DarkModeTrue3xImage';
export { StateboxFailedDarkImage, default as StateboxFailedDarkImageDefault } from './StateboxFailedDarkImage';
export { StateboxFailedDark2xImage, default as StateboxFailedDark2xImageDefault } from './StateboxFailedDark2xImage';
export { StateboxFailedDark3xImage, default as StateboxFailedDark3xImageDefault } from './StateboxFailedDark3xImage';
export { StateboxFailedImage, default as StateboxFailedImageDefault } from './StateboxFailedImage';
export { StateboxFailed2xImage, default as StateboxFailed2xImageDefault } from './StateboxFailed2xImage';
export { StateboxFailed3xImage, default as StateboxFailed3xImageDefault } from './StateboxFailed3xImage';

// Type exports
export type { BuildInSimImageProps } from './BuildInSimImage';
export type { BuildInSim2xImageProps } from './BuildInSim2xImage';
export type { BuildInSim3xImageProps } from './BuildInSim3xImage';
export type { Cm100glteImageProps } from './Cm100glteImage';
export type { Cm100glte2xImageProps } from './Cm100glte2xImage';
export type { Cm100glte3xImageProps } from './Cm100glte3xImage';
export type { ConnectedGraphic1ImageProps } from './ConnectedGraphic1Image';
export type { ConnectedGraphic2ImageProps } from './ConnectedGraphic2Image';
export type { ConnectedGraphic3ImageProps } from './ConnectedGraphic3Image';
export type { ConnectedGraphicImageProps } from './ConnectedGraphicImage';
export type { ConnectedGraphic2x1ImageProps } from './ConnectedGraphic2x1Image';
export type { ConnectedGraphic2x2ImageProps } from './ConnectedGraphic2x2Image';
export type { ConnectedGraphic2x3ImageProps } from './ConnectedGraphic2x3Image';
export type { ConnectedGraphic2xImageProps } from './ConnectedGraphic2xImage';
export type { ConnectedGraphic3x1ImageProps } from './ConnectedGraphic3x1Image';
export type { ConnectedGraphic3x2ImageProps } from './ConnectedGraphic3x2Image';
export type { ConnectedGraphic3x3ImageProps } from './ConnectedGraphic3x3Image';
export type { ConnectedGraphic3xImageProps } from './ConnectedGraphic3xImage';
export type { DashCamBlacklistedImageProps } from './DashCamBlacklistedImage';
export type { DashCamBlacklisted2xImageProps } from './DashCamBlacklisted2xImage';
export type { DashCamBlacklisted3xImageProps } from './DashCamBlacklisted3xImage';
export type { DashCamFailedImageProps } from './DashCamFailedImage';
export type { DashCamFailed2xImageProps } from './DashCamFailed2xImage';
export type { DashCamFailed3xImageProps } from './DashCamFailed3xImage';
export type { FilelistTipsSensorTouchBlackvue1ImageProps } from './FilelistTipsSensorTouchBlackvue1Image';
export type { FilelistTipsSensorTouchBlackvueImageProps } from './FilelistTipsSensorTouchBlackvueImage';
export type { FilelistTipsSensorTouchBlackvue2x1ImageProps } from './FilelistTipsSensorTouchBlackvue2x1Image';
export type { FilelistTipsSensorTouchBlackvue2xImageProps } from './FilelistTipsSensorTouchBlackvue2xImage';
export type { FilelistTipsSensorTouchBlackvue3x1ImageProps } from './FilelistTipsSensorTouchBlackvue3x1Image';
export type { FilelistTipsSensorTouchBlackvue3xImageProps } from './FilelistTipsSensorTouchBlackvue3xImage';
export type { FilelistTipsSensorTouchFleeta1ImageProps } from './FilelistTipsSensorTouchFleeta1Image';
export type { FilelistTipsSensorTouchFleetaImageProps } from './FilelistTipsSensorTouchFleetaImage';
export type { FilelistTipsSensorTouchFleeta2x1ImageProps } from './FilelistTipsSensorTouchFleeta2x1Image';
export type { FilelistTipsSensorTouchFleeta2xImageProps } from './FilelistTipsSensorTouchFleeta2xImage';
export type { FilelistTipsSensorTouchFleeta3x1ImageProps } from './FilelistTipsSensorTouchFleeta3x1Image';
export type { FilelistTipsSensorTouchFleeta3xImageProps } from './FilelistTipsSensorTouchFleeta3xImage';
export type { SimIccidImage344ImageProps } from './SimIccidImage344Image';
export type { SimIccidImage3442xImageProps } from './SimIccidImage3442xImage';
export type { SimIccidImage3443xImageProps } from './SimIccidImage3443xImage';
export type { SimIccidImage345ImageProps } from './SimIccidImage345Image';
export type { SimIccidImage3452xImageProps } from './SimIccidImage3452xImage';
export type { SimIccidImage3453xImageProps } from './SimIccidImage3453xImage';
export type { TouchSensorImageProps } from './TouchSensorImage';
export type { TouchSensor2xImageProps } from './TouchSensor2xImage';
export type { TouchSensor3xImageProps } from './TouchSensor3xImage';
export type { WifiHotspotImageProps } from './WifiHotspotImage';
export type { WifiHotspot2xImageProps } from './WifiHotspot2xImage';
export type { WifiHotspot3xImageProps } from './WifiHotspot3xImage';
export type { DarkModeFalse1ImageProps } from './DarkModeFalse1Image';
export type { DarkModeFalse2ImageProps } from './DarkModeFalse2Image';
export type { DarkModeFalseImageProps } from './DarkModeFalseImage';
export type { DarkModeFalse2x1ImageProps } from './DarkModeFalse2x1Image';
export type { DarkModeFalse2x2ImageProps } from './DarkModeFalse2x2Image';
export type { DarkModeFalse2xImageProps } from './DarkModeFalse2xImage';
export type { DarkModeFalse3x1ImageProps } from './DarkModeFalse3x1Image';
export type { DarkModeFalse3x2ImageProps } from './DarkModeFalse3x2Image';
export type { DarkModeFalse3xImageProps } from './DarkModeFalse3xImage';
export type { DarkModeTrue1ImageProps } from './DarkModeTrue1Image';
export type { DarkModeTrue2ImageProps } from './DarkModeTrue2Image';
export type { DarkModeTrueImageProps } from './DarkModeTrueImage';
export type { DarkModeTrue2x1ImageProps } from './DarkModeTrue2x1Image';
export type { DarkModeTrue2x2ImageProps } from './DarkModeTrue2x2Image';
export type { DarkModeTrue2xImageProps } from './DarkModeTrue2xImage';
export type { DarkModeTrue3x1ImageProps } from './DarkModeTrue3x1Image';
export type { DarkModeTrue3x2ImageProps } from './DarkModeTrue3x2Image';
export type { DarkModeTrue3xImageProps } from './DarkModeTrue3xImage';
export type { StateboxFailedDarkImageProps } from './StateboxFailedDarkImage';
export type { StateboxFailedDark2xImageProps } from './StateboxFailedDark2xImage';
export type { StateboxFailedDark3xImageProps } from './StateboxFailedDark3xImage';
export type { StateboxFailedImageProps } from './StateboxFailedImage';
export type { StateboxFailed2xImageProps } from './StateboxFailed2xImage';
export type { StateboxFailed3xImageProps } from './StateboxFailed3xImage';

// Utility types
export interface ImageComponentProps {
  className?: string;
  width?: number | string;
  height?: number | string;
  alt?: string;
  style?: React.CSSProperties;
  onClick?: () => void;
  onLoad?: () => void;
  onError?: () => void;
}

export interface LazyImageProps extends ImageComponentProps {
  lazy?: boolean;
  placeholder?: React.ReactNode;
  cdnBase?: string;
}
